version: '3.7'

services:
    php71-cli:
        build:
            context: ./docker
            dockerfile: php71-cli.docker
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            - ./:/app:delegated
            - composer:/root/.composer/cache

volumes:
    composer:
