version: '3.7'

services:
#    php71-cli:
#        build:
#            context: ./docker
#            dockerfile: php71-cli.dockerfile
#        environment:
#            COMPOSER_MEMORY_LIMIT: -1
#        volumes:
#            - ./:/app:delegated
#            - composer:/root/.composer/cache
#
#    php72-cli:
#        build:
#            context: ./docker
#            dockerfile: php72-cli.dockerfile
#        environment:
#            COMPOSER_MEMORY_LIMIT: -1
#        volumes:
#            - ./:/app:delegated
#            - composer:/root/.composer/cache

    php81-cli:
        build:
            context: .
            target: php81_cli
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            # The "cached" option has no effect on Linux but improves performance on Mac
            - ./:/app:rw,cached
            - composer:/root/.composer/cache
            # If you develop on Mac you can remove the var/ directory from the bind-mount
            # for better performance by enabling the next line
            - /app/var/cache

volumes:
    composer:
