version: '3.4'

services:
    php:
        build:
            context: .
            target: php
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            # The "cached" option has no effect on Linux but improves performance on Mac
            - ./:/app:rw,cached
            - composer:/root/.composer/cache
            # If you develop on Mac you can remove the var/ directory from the bind-mount
            # for better performance by enabling the next line
            - /app/var/cache

volumes:
    composer:
